### ISSUE TITLE
Integration Library with ASP.NET Core?

### ISSUE THREAD

**Issue by billpratt** [IdentityModel/ClaimsTransformationMiddleware.Katana#1]
Do you have plans to create an ASP.NET Core integration library for this? If you want to create the project I could submit a PR

**Comment by leastprivilege** [comment]
it's built-in in core.

**Comment by billpratt** [comment]
In what Core? IdentityModel or ASP.NET Core? I'm thinking of the use case when using net451 in a new core project. Similar to this guy: https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation.Integration.AspNetCore

**Comment by brockallen** [comment]
In ASP.NET Core this is built-in.
